//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class glue_schema_registry_schema : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal glue_schema_registry_schema(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(glue_schema_registry_schema obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~glue_schema_registry_schema() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GsrSerDePINVOKE.delete_glue_schema_registry_schema(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public glue_schema_registry_schema(string schema_name, string schema_def, string data_format) : this(GsrSerDePINVOKE.new_glue_schema_registry_schema(schema_name, schema_def, data_format), true) {
  }

  public string get_schema_name() {
    string ret = GsrSerDePINVOKE.glue_schema_registry_schema_get_schema_name(swigCPtr);
    return ret;
  }

  public string get_schema_def() {
    string ret = GsrSerDePINVOKE.glue_schema_registry_schema_get_schema_def(swigCPtr);
    return ret;
  }

  public string get_data_format() {
    string ret = GsrSerDePINVOKE.glue_schema_registry_schema_get_data_format(swigCPtr);
    return ret;
  }

}
