//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class glue_schema_registry_serializer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal glue_schema_registry_serializer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(glue_schema_registry_serializer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~glue_schema_registry_serializer() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GsrSerDePINVOKE.delete_glue_schema_registry_serializer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public glue_schema_registry_serializer() : this(GsrSerDePINVOKE.new_glue_schema_registry_serializer(), true) {
  }

  public mutable_byte_array encode(read_only_byte_array array, string transport_name, glue_schema_registry_schema gsr_schema) {
    global::System.IntPtr cPtr = GsrSerDePINVOKE.glue_schema_registry_serializer_encode(swigCPtr, read_only_byte_array.getCPtr(array), transport_name, glue_schema_registry_schema.getCPtr(gsr_schema));
    mutable_byte_array ret = (cPtr == global::System.IntPtr.Zero) ? null : new mutable_byte_array(cPtr, true);
    return ret;
  }

}
